### ISSUE TITLE
[Bug Report][Windows 10] Both Point-and-Clicks failed when blank space exist on the file path

### ISSUE THREAD

**Issue by Stevearzh** [lhl2617/VSLilyPond-PDF-preview#110]
First of all, I want to say thank you. 

I'm a newbie for LilyPond, this VSLilyPond plugin really helps me a lot, it is awesome.

---

I met this problem when I try using VSLilyPond: 

1. When Forward (Score to PDF), the error message is:
```
[ERROR]: Error: No valid PDF location can be found from the cursor
```

2. When Backward (PDF to Score), the error message is:
```
[ERROR]: Error: cannot open file:///e%3A/LilyPond%2520Sheet/test.ly. Detail: Unable to read file 'e:\LilyPond%20Sheet\test.ly' (Error: Unable to resolve nonexistent file 'e:\LilyPond%20Sheet\test.ly')
```

And it works as expect if I change the folder name from `LilyPond Sheet` to just `LilyPond`.

I check the code, maybe we should  use `decodeURIComponent` for `fsPath` here? https://github.com/lhl2617/VSLilyPond-PDF-preview/blob/master/src/extension/pdf-goto.ts#L86

I'm not familiar with VSCode plugin development, please forgive me if I'm wrong.

**Comment by lhl2617** [comment]
Hey @Stevearzh -- thanks for reporting this and also investigating. 

> I check the code, maybe we should use decodeURIComponent for fsPath here? https://github.com/lhl2617/VSLilyPond-PDF-preview/blob/master/src/extension/pdf-goto.ts#L86

Do you want to try this? :) There is a dev guide [here](https://github.com/lhl2617/VSLilyPond-PDF-preview#development).

Otherwise, I can have a look over the weekend.

**Comment by Stevearzh** [comment]
@lhl2617 Thanks for the guide, I didn't notice it at the first time.

It takes me a while to configure the development environment on Windows, sorry for that...

And I met another problem when debugging the plugin

![image](https://user-images.githubusercontent.com/4365999/140105329-b4af628b-509a-4f1f-b6c6-08803eeecfeb.png)

the pdf viewer is always in loading status, I'm not sure which step I did wrong

**Comment by lhl2617** [comment]
@Stevearzh can you try this without any changes off the `main` branch?

**Comment by aron-hanowski** [comment]
I was able to fix this by adding `decodeURIComponent` [here](https://github.com/lhl2617/VSLilyPond-PDF-preview/blob/master/src/pdfjs-custom/main.ts#L46).
This should solve the issue for both directions.

**Comment by lhl2617** [comment]
Thanks so much @aron-hanowski !


@Stevearzh can you double check if the issue is resolved?

**Comment by Stevearzh** [comment]
Yes it is resolved. Thank you guys! @aron-hanowski @lhl2617
