### ISSUE TITLE
When scrolled down, after the refresh the scroll position is reset

### ISSUE THREAD

**Issue by Apostolique** [lhl2617/VSLilyPond-PDF-preview#19]
When I edit the LilyPond text file and save, the PDF gets regenerated but the scroll position isn't preserved.

**Comment by lhl2617** [comment]
Can repro--thanks for this.

I'm looking into overhauling the entire PDF rendering thing--I've been following another extension that has inherent problems like these (bad choice), but I found another extension that does things more nicely and does fix this. Bear with me for a moment with this--I'll need some time to work on it

**Comment by lhl2617** [comment]
Fixed in 0.1.9 #23 :)
