### ISSUE TITLE
Feature request: Focus code with point and click

### ISSUE THREAD

**Issue by Apostolique** [lhl2617/VSLilyPond-PDF-preview#35]
In my setup, I do a vertical split. On the left I have my LilyPond code and on the right I have the PDF preview.

When I click on a note in the PDF with point and click, the note gets highlighted and the cursor gets moved, but the code tab / split doesn't get focused.

If instead I don't have a vertical split and the code and PDF share the same window, then vscode will switch to the code tab and it will be correctly focused.

**Comment by lhl2617** [comment]
Fix coming :)

**Comment by lhl2617** [comment]
Implemented in 0.2.3 #36
