### ISSUE TITLE
textedit protocol is parsed badly(?)

### ISSUE THREAD

**Issue by Apostolique** [lhl2617/VSLilyPond-PDF-preview#37]
In the textedit protocol, a link will look like this: `textedit://c:/super-lilypond.ly:34:2:3`

Multiple variables can be extracted:

* file: `c:/super-lilypond.ly`
* line: `34`
* char: `2`
* column: `3`

When I click on a note, it looks like I end up at `column + 1` which puts the cursor to the right of a note instead of at the start. 
(For a note like `ees`, the cursor ends up at `e|es` instead of `|ees`.)

**Comment by lhl2617** [comment]
Ah yes indeed--it wasn't; thanks for flagging! I was confused with those numbers based on the invoke editor script

will fix today

**Comment by lhl2617** [comment]
Fixed in 0.2.4 #38 -- now also highlights the entire word whenever possible (`|ees`)
