### ISSUE TITLE
Point and click opens a new source text instance

### ISSUE THREAD

**Issue by Apostolique** [lhl2617/VSLilyPond-PDF-preview#65]
This happened last month and I haven't run into that issue again so it might have already been fixed? Submitting this anyway just in case.

Here is a recording of the bug I ran into: <https://youtu.be/tiYksWcjNZM?t=1590>

Every time I would click a note in the PDF, it would open a new source instance even though it was already opened.

**Comment by lhl2617** [comment]
ACK--on holiday, will look into it next week, thanks for reportingn

**Comment by lhl2617** [comment]
Should already be fixed in #23
